version: "3.8"

services:
  db:
    image: docker.io/library/mysql:8.4
    container_name: nextcloud-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: secret
    volumes:
      - nextcloud-db:/var/lib/mysql
    networks:
      - vaultcloud-net

  app:
    image: docker.io/library/nextcloud
    container_name: nextcloud-app
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: secret
      MYSQL_HOST: db
    volumes:
      - nextcloud-data:/var/www/html
    networks:
      - vaultcloud-net
    depends_on:
      - db

volumes:
  nextcloud-db:
  nextcloud-data:

networks:
  vaultcloud-net:
    driver: bridge
